# Generated by Django 4.2.7 on 2023-11-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_sharing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
