# Generated by Django 4.2.7 on 2023-11-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun', models.CharField(choices=[('FEM', 'she/her'), ('MAS', 'he/him'), ('NEU', 'they/them'), ('NON', 'xe/xem')], default='Please select', max_length=3)),
                ('website', models.URLField(blank=True, null=True)),
                ('social', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='profile_background_image')),
            ],
        ),
    ]
