# Generated by Django 4.2.7 on 2023-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_location_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AddField(
            model_name='profile',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='joined_date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True, null=True, verbose_name='personal_website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, null=True, verbose_name='social_links'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background_image', verbose_name='profile_background_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='profile_image'),
        ),
    ]
