# Generated by Django 4.2.7 on 2023-11-20 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_remove_profile_social_remove_profile_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background_image', verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True, null=True, verbose_name='Personal website'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronoun',
            field=models.CharField(choices=[('NOT', 'prefer not to say'), ('FEM', 'she/her'), ('MAS', 'he/him'), ('NEU', 'they/them'), ('NON', 'xe/xem')], default='Please select', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, null=True, verbose_name='Social links'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
