# Generated by Django 4.2.7 on 2023-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_background_image_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pronoun',
            field=models.CharField(choices=[('NOT', 'prefer not to say'), ('FEM', 'she/her'), ('MAS', 'he/him'), ('NEU', 'they/them'), ('NON', 'xe/xem')], default='NOT', max_length=3),
        ),
    ]
